server:
  port: 5000

spring:
  #mongodb configurations
  data:
    mongodb:
      uri: ${MONGODB_URI}
  
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

github:
  client:
    id: ${GITHUB_CLIENT_ID}
    secret: ${GITHUB_CLIENT_SECRET}

gemini:
  api:
    key: ${GEMINI_API_KEY}

jwt:
  secret: ${JWT_SECRET}