# Production Configuration for Render Deployment
# Set these environment variables in Render Dashboard

server:
  port: 8080
  address: 0.0.0.0

  # MongoDB Atlas Configuration
  # Get connection string from: https://cloud.mongodb.com
  data:
    mongodb:
      uri: ${MONGODB_URI}  # Required: MongoDB Atlas connection string
  
  # OAuth2 Configuration
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}     # Required: GitHub OAuth App Client ID
            client-secret: ${GITHUB_CLIENT_SECRET} # Required: GitHub OAuth App Secret
            scope: user:email,repo
            redirect-uri: ${CALLBACK_URI:https://your-app.onrender.com/api/auth/callback}

# GitHub API Configuration
# Create OAuth App at: https://github.com/settings/developers
github:
  client:
    id: ${GITHUB_CLIENT_ID}      # Same as above
    secret: ${GITHUB_CLIENT_SECRET}  # Same as above
  redirect:
    uri: ${CALLBACK_URI:https://your-app.onrender.com/api/auth/callback}

# JWT Token Configuration
jwt:
  secret: ${JWT_SECRET}          # Required: Strong secret (32+ chars)
  expiration: ${JWT_EXPIRATION:86400000}  # 24 hours in milliseconds

# Google Gemini AI Configuration
# Get API key from: https://makersuite.google.com/app/apikey
gemini:
  api:
    key: ${GEMINI_API_KEY}       # Required: Gemini API key

# Application URLs
app:
  base-url: ${BASE_URL:https://your-app.onrender.com}
  
# Logging Configuration
logging:
  level:
    com.project.Readme: INFO
    org.springframework.security: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"